### ISSUE TITLE
"Unable to find EVS commandline utilities" during first-time setup via docker-compose

### ISSUE THREAD

**Issue by mayermatt** [snorre-k/idrive-docker#16]
I'm seeing the "Unable to find EVS commandline utilities" issue in first-time setup, and was wondering if there's something I've got wrong, or if you have a sense of what a more permanent solution might look like instead of my workaround.

The issue is also reproducible if I clone the repo and build from scratch.

Walking through my setup:

1. Added a service to my docker-compose file as follows:
 ```
idrive:
    container_name: idrive
    hostname: <CUSTOM HOSTNAME>
    image: snorre0815/idrive-docker:latest
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    volumes:
      # Host directory to back up (read-only)
      - "/home/<USERNAME>:/home/backup:ro"
      # Storage of persistent config, etc.
      - "/home/<USERNAME>/docker/idrive/config:/opt/IDriveForLinux/idriveIt"
```

2. Prior to first-time run, I pre-created the idrive/config directory referenced in my volume mapping and gave it a `chmod +777` to make sure there are no permission issues, like some have described [here](https://forums.unraid.net/topic/47584-anyone-got-idrive-working-on-unraid/page/4/).

Running this to do first-time setup, per your README:
    `docker compose exec -it idrive ./idrive --account-setting`
Yields this error:
    `Unable to find EVS commandline utilities. Reinstall app or contact support for more information.`

Running this to try and kick it into doing a reinstall (has previously been a functioning workaround):
    `docker compose exec -it idrive ./idrive --check-update`
Yields this error:
    `Login to your IDrive account using Login option from the main menu and try again.`

Running this, just for experimentation:
    `docker compose exec -it idrive ./idrive --login`
Yields this error:
    `Enter your IDrive username: <TYPED IN>`
    `Your account is not configured. Configure using Configure/Reconfigure your account option from the main menu and try again.`

I've been able to work around this by doing the following, one line at a time:
```
# Enter the container and manually reinstall
docker compose exec -it idrive bash
cd /tmp    
curl -O https://www.idrivedownloads.com/downloads/linux/download-for-linux/linux-bin/idriveforlinux.bin
chmod +x idriveforlinux.bin
./idriveforlinux.bin --install
exit

# Perform first-time setup
docker compose exec -it idrive ./idrive --account-setting

# Cycle the container to make sure it's all stable after bringing down and back up
docker compose down idrive
docker compose up -d idrive
```

**Comment by mayermatt** [comment]
Immediately after posting, I think I've identified the cause. I stopped the container, deleted all local config files, **and removed all volume mappings from the compose file**. I was then able to run the --account-setting setup without error. Of course, without volume mappings, the configuration would be lost if the container is ever brought down, which is no good.

### The Issue
Right now, this repo recommend mapping a folder on the host machine to the /opt/IDriveForLinux/idriveIt folder. Unfortunately, the first-time install script (`idriveforlinux.bin --install`) during build places binaries (these must be the fabled "EVS utilities") inside the `/opt/IDriveForLinux/idriveIt` directory. Then, those binaries are hidden by the volume mapping when the container is brought up.

### Short-Term Workaround
I was able to successfully resolve this by mapping the appropriate subdirectories of `idriveIt` instead of the entire path. I changed my volume mapping from this:
` - "/home/<USERNAME>/docker/idrive/config:/opt/IDriveForLinux/idriveIt"`

to this:
` - "/home/<USERNAME>/docker/idrive/config/cache:/opt/IDriveForLinux/idriveIt/cache"`
` - "/home/<USERNAME>/docker/idrive/config/user_profile:/opt/IDriveForLinux/idriveIt/user_profile"`

After bringing the container down and back up, I'm able to successfully log in and make configuration changes, and it all persists if I bounce the container down and up again.
 
### Recommended Fix
I would propose updating the docker-compose file and README to use these more fine-grained volume mappings.

In the README, should also replace any references to the `docker-compose` command with `docker compose` (no hyphen), since the hyphenated version is obsolete and no longer works in newer versions of docker-compose.

**Alternatively** you could have your start.sh script just re-run the installer on startup, and toss a file in the config directory as a "setup complete" flag to avoid running multiple times. This seems less than ideal since it's less resilient to changes from IDrive devs. It doesn't properly draw a line between "binaries that should be included in the image" vs. "user-managed / config data that should be mapped into the host" -- meaning if they add more binaries to the idriveIt folder, you can't simply push out an updated image.

**Comment by snorre-k** [comment]
Your findings are absolutely correct. The problem comes from the design of the iDrive Linux application, which mixes config data and binaries into the same folder (`/opt/IDriveForLinux/idriveIt`). It looks like the application was never designed to be run in a container.

Now the good points:

- when you run the image as documented with a **docker volume** (not a mount!), the volume gets pre filled with the already existing files. These files and the additional config are stored persistent
- also when you do not specify a dedicated volume, a docker volume is implicitly created and stores the mentioned binary and config files. This is done with the `VOLUME /opt/IDriveForLinux/idriveIt` directive in the build file.

The bad news:

- This does not work with bind mounts, as they just overlay the existing folder.

I will try to add your bind mount workaround to the documentation and as a separate docker-compose.yaml file.

**Comment by mayermatt** [comment]
Ah, I see! This behavior:

> when you run the image as documented with a docker volume (not a mount!), the volume gets pre filled with the already existing files.

Is something I was unaware of. And I had previously thought this was false, **because I apparently had a pre-existing idrive volume with data in it** that I was not aware of, meaning the pre-filling didn't occur. I suspect it was from a previous attempt at getting IDrive running in Docker years ago, probably with a different container that wanted it mounted at a different directory depth.

Now that this is squared away, I...

1. Deleted my old idrive volume, configured docker-compose to use your volume-based approach, and verified that it works great. 
2. Added a second container from scratch that uses the binding mount approach, and verified that it works great as well.

So all your documentation looks good. Many thanks for the updates!



P.S. - For posterity, here's a bonus issue + solution that can arose when trying to set up your Docker image. (The issue is in no way caused by your Docker image, but others could perhaps run into it as well, so I thought I'd post it _somewhere_):

- IDrive's servers use MAC addresses to uniquely identify a computer.
- I have two physical computers, both independently running IDrive (`snorre0815/idrive-docker:latest`) via their own docker-compose files.
- For the default docker bridge network, it assigns MAC addresses to containers based on the IP address of a container
- ...and since they are two physical computers with two independent bridge networks, containers can have overlapping IP addresses, in which case they will have overlapping MAC addresses.
- In my setup, my IDrive containers got the same IP addresses + MAC addresses, which was massively destabilizing for IDrive. It introduced weird race conditions where, depending on which container the IDrive servers most recently communicated with, the online dashboard would sporadically change the name of the computer and the backup drive. The two computers were also physically incapable of backing up to different storage locations within IDrive - it kept merging the two filesystems together on the server, even though each one *thought* they were two storage locations under two different names.

My fix was to manually assign a MAC address to each container:
```
  idrive:
    container_name: idrive
    hostname: <HOSTNAME>
    image: snorre0815/idrive-docker:latest
    restart: unless-stopped
    environment:
      - TZ=<TIMEZONE>
    # Do not have two different IDrive containers with the same MAC addresses!
    # Generate a decent one like so:  printf '02:%02x:%02x:%02x:%02x:%02x\n' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
    mac_address: <XX:XX:XX:XX:XX:XX>
    volumes:
      <VOLUMES>
```

Alternatively, I assume that using the `macvlan` network driver in Docker would resolve this.
